name: 'Update Corretto version'
description: 'Update the version based on upstream configuration'

inputs:
    upstream:
        description: 'upstream remote suffix'
        required: true
    version-branch:
        description: 'Branch to update version of'
        required: true
outputs:
    status:
        description: 'Status of the update of the version'
runs:
    using: "composite"
    steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Update the version.txt file as necessary
          id: update-version
          shell: bash
          run: python $GITHUB_ACTION_PATH/update_version.py ${{ inputs.upstream }} ${{ inputs.version-branch }}
